# Gitleaks configuration for Carpool project
# This file defines rules for detecting secrets in git repos

title = "Carpool Secrets Detection"

[extend]
# Use default gitleaks rules
useDefault = true

[[rules]]
id = "azure-client-secret"
description = "Azure Client Secret"
regex = '''['\"]?[a-zA-Z0-9~._-]{34,}['\"]?'''
path = '''\.env|\.config|config\.'''
keywords = ["client_secret", "clientSecret", "AZURE_CLIENT_SECRET"]

[[rules]]
id = "azure-connection-string"  
description = "Azure Connection String"
regex = '''DefaultEndpointsProtocol=https;AccountName=[a-zA-Z0-9]+;AccountKey=[a-zA-Z0-9+/]+=*;EndpointSuffix=core\.windows\.net'''

[[rules]]
id = "cosmos-db-key"
description = "Cosmos DB Primary/Secondary Key"
regex = '''[a-zA-Z0-9+/]{88}=='''
keywords = ["cosmosdb", "documentdb", "primary", "secondary"]

[[rules]]
id = "jwt-secret"
description = "JWT Secret Key"
regex = '''['\"]?[a-zA-Z0-9+/=]{32,}['\"]?'''
keywords = ["jwt", "JWT_SECRET", "jwtSecret"]

[[rules]]
id = "database-url"
description = "Database Connection URL with credentials"
regex = '''[a-zA-Z][a-zA-Z0-9+.-]*://[a-zA-Z0-9._-]+:[a-zA-Z0-9._%-]+@[a-zA-Z0-9._-]+'''

# Allowlist for false positives
[allowlist]
description = "Ignore false positives in generated files, documentation, and test files"

# File patterns to ignore
files = [
    '''\.lock$''',
    '''package-lock\.json$''',
    '''\.log$''',
    '''\.md$''',
    '''\.txt$''',
    '''\.html$''',
    '''\.json$''',
    '''\.sample\.json$''',
    '''\.template\..*''',
    '''\.example\..*''',
    '''\.bicep$''',
    '''\.mjs$'''
]

# Directory paths to ignore
paths = [
    '''backend/coverage/''',
    '''frontend/\.next/''',
    '''node_modules/''',
    '''\.git/''',
    '''coverage/''',
    '''dist/''',
    '''build/''',
    '''docs/''',
    '''scripts/''',
    '''infra/''',
    '''test/.*''',
    '''tests/.*''',
    '''spec/.*''',
    '''__tests__/.*''',
    '''\.test\.''',
    '''\.spec\.''',
    '''example.*''',
    '''sample.*''',
    '''mock.*''',
    '''fixture.*'''
]

# Regex patterns for known false positives
regexes = [
    # OpenAPI schema references
    '''schema.*components/schemas''',
    '''ErrorResponse''',
    '''ValidationErrorResponse''',
    '''CreateTripRequest''',
    '''UpdateTripRequest''',
    '''HealthResponse''',
    '''UpdateUserRequest''',
    
    # Azure Bicep infrastructure patterns
    '''enableLogAccessUsingOnlyResourcePermissions''',
    '''DocumentDB/databaseAccounts''',
    '''Microsoft\.DocumentDB''',
    '''Microsoft\..*@\d{4}-\d{2}-\d{2}''',
    
    # File path patterns in scripts
    '''frontend/src/hooks/usePerformance''',
    '''backend/src/middleware/sanitization''',
    '''backend/src/monitoring/monitoring''',
    '''backend/src/.*\.ts''',
    '''frontend/src/.*\.tsx?''',
    
    # Next.js build artifacts (specific encryption keys from builds)
    '''encryptionKey.*HbI/lNy/OhB8nXSECJKa5eEZ02jWhw2wtnCuGkdXi\+4=''',
    
    # Generic patterns for legitimate code
    '''components/schemas/.*''',
    '''/\$ref.*components''',
    '''\.\.\..*Database.*Microsoft\.''',
    
    # Test and example patterns
    '''(?i)example''',
    '''(?i)sample''',
    '''(?i)placeholder''',
    '''(?i)your[_-]?key[_-]?here''',
    '''(?i)replace[_-]?with''',
    '''(?i)dummy''',
    '''(?i)fake'''
]
