name: Node.js Setup

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: ''
    outputs:
      cache-hit:
        description: 'A boolean value to indicate if a cache hit occurred'
        value: ${{ steps.cache-node-modules.outputs.cache-hit }}

jobs:
  setup:
    name: Node.js Setup
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-node-modules.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory && format('{0}/package-lock.json', inputs.working-directory) || 'package-lock.json' }}

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ inputs.working-directory && format('{0}/node_modules', inputs.working-directory) || 'node_modules' }}
          key: ${{ runner.os }}-node-${{ hashFiles(inputs.working-directory && format('{0}/package-lock.json', inputs.working-directory) || 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ${{ inputs.working-directory || '.' }}
