export * from "./types";
export * from "./validations";
export * from "./schemas/trip-params";
export * from "./schemas/user-params";
export * from "./schemas/chat-schemas";
export * from "./schemas/message-schemas";
export { forgotPasswordSchema, resetPasswordSchema, changePasswordSchema, } from "./validations";
export * from "./utils";
export declare const APP_CONFIG: {
    MAX_PASSENGERS_PER_TRIP: number;
    DEFAULT_TRIP_COST: number;
    NOTIFICATION_DELAY_MINUTES: number;
    MAX_SWAP_REQUESTS_PER_DAY: number;
    SESSION_TIMEOUT_HOURS: number;
    PASSWORD_MIN_LENGTH: number;
};
export declare const ERROR_CODES: {
    VALIDATION_ERROR: string;
    NOT_FOUND: string;
    UNAUTHORIZED: string;
    FORBIDDEN: string;
    CONFLICT: string;
    INTERNAL_ERROR: string;
    RATE_LIMITED: string;
};
export declare const SUCCESS_MESSAGES: {
    USER_CREATED: string;
    USER_UPDATED: string;
    TRIP_CREATED: string;
    TRIP_UPDATED: string;
    TRIP_CANCELLED: string;
    SWAP_REQUEST_SENT: string;
    SWAP_REQUEST_ACCEPTED: string;
    SWAP_REQUEST_REJECTED: string;
};
export * from "./types";
export * from "./validations";
export type { User, Trip, Schedule, SwapRequest, CreateTripRequest, UpdateTripRequest, JoinTripRequest, ApiResponse, PaginatedResponse, TripStatus, UserPreferences, Message, ChatRoom, ChatParticipant, Notification, NotificationType, MessageType, RealTimeEvent, SendMessageRequest, CreateChatRequest, UpdateMessageRequest, CreateNotificationRequest, ChatRoomWithUnreadCount, MessageWithSender, TripStats, Child, Location, WeeklyScheduleTemplateSlot, DriverWeeklyPreference, RideAssignment, CreateUserRequest, ChangePasswordRequest, SubmitWeeklyPreferencesRequest, GenerateScheduleRequest, CreateChildRequest, UpdateChildRequest, } from "./types";
export type { Family, DayPreference } from "./types";
export type { Preference, Assignment } from "./types";
