name: setup-node

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
      - run: npm ci --ignore-scripts

inputs:
  node-version:
    description: "Node.js version"
    required: true 